import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {createStudyApp} from './study-app.mjs';
import {createBank,originalEnglish,beforeAnswer,answerFeedback,loadRepositoryBank,MISSING_EXPLANATION} from './study-bank.mjs';
import {ACCESS,REFRESH} from './study-auth.mjs';
const ORIGIN='https://pediarounds-render-staging.onrender.com';
const env={RENDER_EXTERNAL_URL:ORIGIN,PEDIAROUNDS_EXTERNAL_BACKEND:'enabled',PEDIAROUNDS_SUPABASE_URL:'https://abcdefghijklmnopqrst.supabase.co',PEDIAROUNDS_SUPABASE_PUBLISHABLE_KEY:'sb_publishable_test'};
const TOKEN='test-access-token-for-fixtures-only',RT='shorttoken12';
const USER={id:'00000000-0000-4000-8000-000000000001',email:'reader@example.test',role:'authenticated',email_confirmed_at:'2026-09-01T00:00:00Z'};
const fixture=(extra={})=>({id:'source-q1',module:'principles',stemEn:'Which option is recorded in this test fixture?',options:[{key:'A',text:'First option'},{key:'B',text:'Second option'}],recalledAnswer:'B',verifiedAnswer:'B',verification:{guideline:'supports',referenceNotes:'Fictional verification fixture; not real medical evidence.'},publishable:true,reviewStatus:'ready_for_publish',originalExplanation:'  Original attached wording.\nSecond source line.  ',sourceRefs:[{sourceName:'Test source',page:1,questionNumber:'1'}],...extra});
function provider({unconfirmed=false,failLogout=false}={}) {
 const calls=[];
 return {calls,fetcher:async(url,options)=>{
  calls.push({url,options});
  if(url.includes('/token?'))return new Response(JSON.stringify({access_token:TOKEN,refresh_token:RT,user:USER}),{status:200});
  if(url.endsWith('/user'))return options.headers.Authorization==='Bearer '+TOKEN?new Response(JSON.stringify({...USER,...(unconfirmed?{email_confirmed_at:null}:{})}),{status:200}):new Response('{}',{status:401});
  if(url.includes('/signup?'))return new Response(JSON.stringify({id:USER.id}),{status:200});
  if(url.includes('/logout?'))return failLogout?new Response('{}',{status:503}):new Response(null,{status:204});
  throw Error('unexpected provider endpoint');
 }};
}
async function running(t,options={}) {
 const p=provider(options),forwarded=[];
 const backend={handle:async(req,res,pathname)=>{forwarded.push({pathname,authorization:req.headers.authorization});req.resume();res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({done:[],seen:[],reviewedCount:0}));return true;}};
 const app=createStudyApp({env:options.env||env,fetcher:p.fetcher,backend,bank:options.bank||createBank([fixture()])});
 const server=createServer(async(req,res)=>{try{if(await app.handle(req,res,new URL(req.url,'http://localhost').pathname))return;res.writeHead(404);res.end();}catch{res.writeHead(500);res.end();}});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>{server.close(resolve);server.closeAllConnections();}));
 const base='http://127.0.0.1:'+server.address().port;
 const request=(path,body,headers={})=>fetch(base+path,{method:body===undefined?'GET':'POST',headers:{...(body===undefined?{}:{Origin:ORIGIN,'Content-Type':'application/json'}),...headers},...(body===undefined?{}:{body:typeof body==='string'?body:JSON.stringify(body)})});
 return {request,app,calls:p.calls,forwarded,base};
}
const cookies=ACCESS+'='+TOKEN+'; '+REFRESH+'='+RT;
test('source wording including whitespace is unchanged',()=>{const q=fixture();assert.equal(originalEnglish(q),q.originalExplanation);});
test('authored English and Arabic teaching are not substituted',()=>{assert.equal(originalEnglish({reasoningEn:'Authored teaching',explanation:'Generic English',explanationAr:'شرح'}),'');});
test('Arabic and presentation-form Arabic are rejected in original text',()=>{for(const originalExplanation of ['English عربي','English \ufefb'])assert.equal(originalEnglish({originalExplanation}),'');});
test('attached explicit English source field is eligible',()=>assert.equal(originalEnglish({sourceExplanationEn:'Original text.'}),'Original text.'));
test('known source placeholders remain missing',()=>assert.equal(originalEnglish({originalExplanation:"Didn't find an answer for this question."}),''));
test('pre-answer payload contains no key, source explanation or hidden teaching',()=>{const q=createBank([fixture()]).get('source-q1');const data=beforeAnswer(q);assert.deepEqual(Object.keys(data).sort(),['id','imageRequired','module','notice','number','options','reviewOnly','text'].sort());assert.doesNotMatch(JSON.stringify(data),/Original attached|recalledAnswer|sourceKey|explanationAr/);});
test('grade uses the source label, not a fixed index assumption',()=>{const q=createBank([fixture({options:[{key:'B',text:'Second option'},{key:'A',text:'First option'}]})]).get('source-q1');assert.equal(answerFeedback(q,0).correct,true);assert.equal(answerFeedback(q,1).correct,false);});
test('missing original source explanation has an honest placeholder',()=>{const q=createBank([fixture({originalExplanation:null,reasoningEn:'Do not use this'})]).get('source-q1');assert.equal(answerFeedback(q,1).explanation,MISSING_EXPLANATION);});
test('uncertain key is not scored',()=>{const q=createBank([fixture({recalledAnswer:'B?'})]).get('source-q1');assert.equal(answerFeedback(q,1).correct,null);assert.equal(answerFeedback(q,null).sourceKey,'B?');});
test('incomplete options are retained as an unscored review',()=>{const q=createBank([fixture({options:[{key:'B',text:'Only recalled choice'}]})]).get('source-q1');assert.equal(q.reviewOnly,true);assert.equal(answerFeedback(q,0).correct,null);});
test('missing required original image prohibits scoring',()=>{const q=createBank([fixture({image:{requiredForQuestion:true,status:'available'}})]).get('source-q1');assert.equal(q.reviewOnly,true);assert.equal(answerFeedback(q,1).correct,null);});
test('publishable false cannot silently become scored content',()=>assert.equal(createBank([fixture({publishable:false})]).get('source-q1').reviewOnly,true));
test('conflicting reviewed/source answers are not scored',()=>assert.equal(createBank([fixture({verifiedAnswer:'A'})]).get('source-q1').reviewOnly,true));
test('invalid or absent selection cannot be graded as correct',()=>{const q=createBank([fixture()]).get('source-q1');for(const v of [-1,2,'1',undefined,null])assert.throws(()=>answerFeedback(q,v));});
test('identifiers are preserved; repeated ID does not create a second question',()=>{const b=createBank([fixture(),fixture()]);assert.equal(b.summary.questionCount,1);assert.equal(b.get('source-q1').id,'source-q1');});
test('conflicting repeated ID is marked review-only',()=>{const b=createBank([fixture(),fixture({recalledAnswer:'A'})]);assert.equal(b.get('source-q1').reviewOnly,true);});
test('declared duplicate resolves to existing canonical ID',()=>{const b=createBank([fixture(),fixture({id:'alias-q1',duplicateOf:'source-q1'})]);assert.equal(b.summary.questionCount,1);assert.equal(b.get('alias-q1').id,'source-q1');});
test('dangling duplicate is retained rather than silently removed',()=>{const b=createBank([fixture({duplicateOf:'absent'})]);assert.equal(b.summary.questionCount,1);assert.equal(b.questions[0].reviewOnly,true);});
test('study entry renders real sign-in controls without embedding questions',async t=>{const {request}=await running(t);const r=await request('/study');const html=await r.text();assert.equal(r.status,200);assert.match(html,/id="login-form"/);assert.match(html,/type="password"/);assert.doesNotMatch(html,/Which option is recorded|Original attached/);assert.match(r.headers.get('content-security-policy'),/frame-ancestors 'none'/);assert.match(r.headers.get('cache-control'),/no-store/);});
test('anonymous visitors cannot retrieve catalog/question/progress/checkpoint',async t=>{const {request,calls}=await running(t);for(const path of ['catalog','question?id=source-q1','progress','checkpoint'])assert.equal((await request('/api/study/'+path)).status,401);assert.equal(calls.length,0);});
test('legacy identity headers do not grant study access',async t=>{const {request}=await running(t);const r=await request('/api/study/catalog',undefined,{'oai-authenticated-user-id':USER.id,'oai-authenticated-user-email':USER.email});assert.equal(r.status,401);});
test('cross-origin sign-in is rejected before forwarding credentials',async t=>{const {request,calls}=await running(t);const r=await request('/api/study/signin',{email:USER.email,password:'test-password'},{Origin:'https://other.example'});assert.equal(r.status,403);assert.equal(calls.length,0);});
test('sign-in establishes secure HttpOnly cookies without exposing tokens',async t=>{const {request}=await running(t);const r=await request('/api/study/signin',{email:USER.email,password:'test-password'});assert.equal(r.status,200);const body=await r.json();assert.equal(body.user.id,USER.id);assert.doesNotMatch(JSON.stringify(body),/test-access|shorttoken|test-password/);assert.equal(r.headers.getSetCookie().length,2);for(const c of r.headers.getSetCookie()){assert.match(c,/HttpOnly/);assert.match(c,/Secure/);assert.match(c,/SameSite=Lax/);assert.match(c,/Max-Age=600/);}});
test('unconfirmed email cannot establish a browser session',async t=>{const {request}=await running(t,{unconfirmed:true});const r=await request('/api/study/signin',{email:USER.email,password:'test-password'});assert.equal(r.status,401);assert.equal(r.headers.get('set-cookie'),null);});
test('ordinary authenticated GET does not recreate cookies after a racing logout',async t=>{const {request}=await running(t);const r=await request('/api/study/session',undefined,{Cookie:cookies});assert.equal(r.status,200);assert.equal(r.headers.get('set-cookie'),null);});
test('12-character provider refresh token is supported',async t=>{const {request}=await running(t);const r=await request('/api/study/refresh',{}, {Cookie:cookies});assert.equal(r.status,200);assert.match(r.headers.getSetCookie()[1],/shorttoken12/);});
test('sign-up requests confirmation and never returns provider credentials',async t=>{const {request}=await running(t);const r=await request('/api/study/signup',{email:USER.email,password:'test-password-123'});assert.equal(r.status,200);const body=await r.json();assert.equal(body.confirmationRequired,true);assert.equal(r.headers.get('set-cookie'),null);assert.doesNotMatch(JSON.stringify(body),/access_token|refresh_token/);});
test('short signup password is rejected without an upstream call',async t=>{const {request,calls}=await running(t);assert.equal((await request('/api/study/signup',{email:USER.email,password:'123'})).status,400);assert.equal(calls.length,0);});
test('logout clears browser cookies even when provider revocation fails',async t=>{const {request}=await running(t,{failLogout:true});const r=await request('/api/study/signout',{}, {Cookie:cookies});assert.equal(r.status,200);assert.equal((await r.json()).remoteRevoked,false);for(const c of r.headers.getSetCookie())assert.match(c,/Max-Age=0/);});
test('authenticated question is safe before answer; original text revealed only on submission',async t=>{const {request}=await running(t);const q=await(await request('/api/study/question?id=source-q1',undefined,{Cookie:cookies})).json();assert.equal(q.id,'source-q1');assert.equal(q.sourceKey,undefined);assert.equal(q.explanation,undefined);const r=await request('/api/study/answer',{id:'source-q1',selectedIndex:1},{Cookie:cookies});assert.equal(r.status,200);const feedback=await r.json();assert.equal(feedback.correct,true);assert.equal(feedback.explanation,fixture().originalExplanation);});
test('cookie-backed progress writes are CSRF-protected',async t=>{const {request,forwarded}=await running(t);const r=await request('/api/study/progress',{completed:[],seen:[]},{Cookie:cookies,Origin:'https://other.example'});assert.equal(r.status,403);assert.equal(forwarded.length,0);});
test('same-origin progress uses the verified cookie token with the existing backend',async t=>{const {request,forwarded}=await running(t);const r=await request('/api/study/progress',{completed:[],seen:[]},{Cookie:cookies});assert.equal(r.status,200);assert.equal(forwarded[0].authorization,'Bearer '+TOKEN);assert.equal(forwarded[0].pathname,'/api/external/progress');});
test('status never claims full migration or a real-user test',async t=>{const {request}=await running(t);const data=await(await request('/study/status')).json();assert.equal(data.browserInterfaceImplemented,true);for(const k of ['fullSiteMigrated','legacyAccountsMigrated','legacyProgressMigrated','originalImagesMigrated','realUserEndToEndTested'])assert.equal(data[k],false);assert.equal(data.bank.scope,'current-github-master-bank-only');assert.doesNotMatch(JSON.stringify(data),/sb_publishable_|test-access/);});
test('repository files and arbitrary asset paths are never served',async t=>{const {request}=await running(t);for(const p of ['/study/.env','/study/README.md','/study/study-auth.mjs','/master-bank/data/q.json'])assert.equal((await request(p)).status,404);});
test('JavaScript asset has a safe MIME type and parses under Node 22',async t=>{const {request}=await running(t);const r=await request('/study/app.mjs');assert.equal(r.status,200);assert.match(r.headers.get('content-type'),/text\/javascript/);execFileSync(process.execPath,['--check',fileURLToPath(new URL('./study-client.mjs',import.meta.url))]);});
test('actual repository bank loads with consistent counts and no scored image dependencies',()=>{const b=loadRepositoryBank();console.log('REPOSITORY_STUDY_BANK',JSON.stringify(b.summary));assert.ok(b.summary.sourceRecords>0);assert.equal(b.summary.practiceCount+b.summary.reviewOnlyCount,b.summary.questionCount);assert.equal(b.summary.originalEnglishCount+b.summary.missingOriginalEnglishCount,b.summary.questionCount);assert.equal(b.questions.filter(q=>q.imageRequired&&!q.reviewOnly).length,0);for(const q of b.questions)assert.doesNotMatch(q.explanation,/\p{Script=Arabic}/u);});
